// This file is autogenerated by VESC Tool

#ifndef CONFGENERATOR__H_
#define CONFGENERATOR__H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MCCONF_SIGNATURE		4014639014
#define APPCONF_SIGNATURE		1095636881

// Functions
int32_t confgenerator._serialize_mcconf(uint8_t *buffer, const mc_configuration *conf);
int32_t confgenerator._serialize_appconf(uint8_t *buffer, const app_configuration *conf);

bool confgenerator._deserialize_mcconf(const uint8_t *buffer, mc_configuration *conf);
bool confgenerator._deserialize_appconf(const uint8_t *buffer, app_configuration *conf);

void confgenerator._set_defaults_mcconf(mc_configuration *conf);
void confgenerator._set_defaults_appconf(app_configuration *conf);

// CONFGENERATOR__H_
#endif
